services:
  web:
    build:
      context: .
    container_name: web
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ${PWD}:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:16-bookworm
    container_name: db
    environment:
      - POSTGRES_USER=igor
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=academy_db
    volumes:
      - ${PWD}/pg_data/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U igor -d academy_db"]
      interval: 5s
      start_period: 5s
      retries: 5
      timeout: 5s
